services:
    web:
        container_name: web
        build: .
        volumes:
          - static:/app/static
        env_file:
          - .env
        depends_on:
          db:
            condition: service_healthy
        restart: always
  
    db:
        container_name: db
        image: postgres:16-alpine
        env_file:
          - .env
        ports:
          - '5400:5432'
        volumes:
          - ./deploy/db:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U$$POSTGRES_USER -d$$POSTGRES_DB"]
          interval: 5s
          timeout: 5s
          retries: 100
        restart: always
    
    redis:
        container_name: redis
        build: deploy/redis
        command: redis-server redis.conf
        ports:
          - '6400:6379'
        volumes:
          - ./deploy/redis:/data
        restart: always
    
    nginx: 
        container_name: nginx
        build: deploy/nginx
        ports:
          - '80:80'
        volumes:
          - static:/static
        depends_on:
          - web
        restart: always

volumes:
    static:
    db:
    redis:
