# Generated by Django 4.2.1 on 2023-06-27 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('key', models.CharField(default=models.CharField(max_length=255, unique=True), max_length=10, unique=True)),
                ('type', models.CharField(default='Software', max_length=255)),
                ('starred', models.BooleanField(default=False, verbose_name='favorite project')),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 22, 53, 29, 63961, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateTimeField()),
                ('closed', models.DateTimeField(default=None)),
                ('timespent', models.PositiveIntegerField(default=0)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.issue_priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.issue_status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.issue_type')),
            ],
        ),
    ]
