# Generated by Django 4.2.1 on 2023-06-27 23:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0002_alter_project_created_delete_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 27, 23, 21, 25, 846561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_num', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('duedate', models.DateTimeField()),
                ('closed', models.DateTimeField(default=None)),
                ('timespent', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.issue_priority')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.issue_status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.issue_type')),
            ],
        ),
    ]
