# Generated by Django 4.2.1 on 2023-07-12 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0005_alter_issue_closed_alter_issue_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 12, 22, 32, 2, 420935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
