# Generated by Django 4.2.2 on 2023-07-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0007_alter_project_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_num',
        ),
    ]
