# Generated by Django 4.2.2 on 2023-07-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0008_remove_issue_issue_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
