# Generated by Django 4.2.2 on 2023-07-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0009_alter_issue_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
