# Generated by Django 4.2.2 on 2023-07-14 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0010_alter_issue_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 characters')]),
        ),
    ]
