# Generated by Django 4.2.2 on 2023-07-15 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0011_alter_project_key_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Key field must contain at least 3 letters')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Name field must contain at least 3 letters')]),
        ),
    ]
