# Generated by Django 4.2.2 on 2023-07-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0012_alter_project_key_alter_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue_priority',
        ),
        migrations.DeleteModel(
            name='Issue_status',
        ),
        migrations.DeleteModel(
            name='Issue_type',
        ),
        migrations.DeleteModel(
            name='Project_type',
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
