# Generated by Django 4.2.2 on 2023-07-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0014_project_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-starred']},
        ),
    ]
