# Generated by Django 4.2.2 on 2023-08-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0016_alter_project_options_remove_issue_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='duedate',
        ),
    ]
