# Generated by Django 4.2.2 on 2023-08-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0017_remove_issue_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='key',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
