# Generated by Django 4.2.2 on 2024-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0019_alter_project_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project'], name='project_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['author'], name='author_idx'),
        ),
    ]
