# Generated by Django 5.0.4 on 2024-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0020_issue_project_idx_project_author_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], max_length=11),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('FULLSTACK', 'Fullstack'), ('FRONTEND', 'Front-end'), ('BACKEND', 'Back-end')], max_length=18),
        ),
    ]