name: testing

run-name: Run the tests

on: workflow_dispatch

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure .env file
        run: |
          cat << EOF > .env
          ${{ secrets.TEST_ENV }}
          EOF

      - name: Start containers
        run: docker compose up -d

      - name: Run tests
        run: docker compose exec web app/manage.py test app/bugtracker/tests/ --keepdb --parallel
